server:
  port: 8088

spring:
  application:
    name: security-service

crypto:
  pkcs11:
    enabled: false
    name: hsm
    # library: /path/to/pkcs11.so
    # slot: 0
    # pin: ${HSM_PIN}
  keys:
    sign-key-01:
      alias: SIGN_KEY_01
      alg: RS256
      jcaAlg: SHA256withRSA
    # Example PS256:
    # sign-key-pss:
    #   alias: SIGN_KEY_PSS
    #   alg: PS256
    #   jcaAlg: RSASSA-PSS

---
spring:
  config:
    activate:
      on-profile: pkcs11

crypto:
  pkcs11:
    enabled: true
    # Set these via env in production
    # library: /usr/local/lib/libCryptoki2_64.so
    # slot: 0
    # pin: ${HSM_PIN}
